name: Publish release
on:
  push:
    branches: [ release ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish release
      run: ./gradlew -PmavenUploadUser="${{ secrets.SONATYPE_USER }}" -PmavenUploadPassword="${{ secrets.SONATYPE_PASSWORD }}" -PsigningKeyId="${{ secrets.pgp_signing_key_id }}" -PsigningKey="${{ secrets.pgp_signing_key }}" -PsigningPassword="${{ secrets.pgp_signing_key_passphrase }}" -Prelease=true -Dorg.gradle.internal.publish.checksums.insecure=true build publish closeAndReleaseRepository
